import { buttonVariants } from "@/components/ui/button"
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from "@/components/ui/tooltip"
import { TracingBeam } from "@/components/ui/tracing-beam"
import { getStory } from "@/utils/actions/database/getStory"
import { Bookmark, BotIcon, MessageSquareText } from "lucide-react"
import { TextGenerateEffect } from "@/components/ui/text-generate-effect"
import Image from "next/image"
import Link from "next/link"
import { redirect } from "next/navigation"

export default async function StoryDetails({
	params,
}: {
	params: { id: string }
}) {
	const story = await getStory(params.id)

	if (!story) {
		redirect("/app")
	}

	const accountInfo = [70, 20, 570]
	const icons = [
		"/icons/follower.png",
		"/icons/book.png",
		"/icons/bookmark.png",
	]

	const reviews = [
		{
			author: "bonndubz",
			content: "you suck lol",
		},
		{
			author: "neofox",
			content: "naaa shudafug up",
		},
		{
			author: "slaviik",
			content: "e",
		},
		{
			author: "peppermint",
			content: "i think i need to go to school",
		},
	]

	return (
		<main className="flex flex-col w-full mx-auto gap-2 py-8 mb-8">
			<div className="flex flex-col w-full mx-auto">
				<TracingBeam className="pt-6 pb-10">
					<h1
						style={{ textShadow: "0em 0em 0.3em rgba(255,255,255,0.6)" }}
						className="text-4xl font-bold mb-5"
					>
						{story.title}
					</h1>
					<TextGenerateEffect
						className="max-w-4xl tracking-wider"
						words={story!!.story!!}
					/>
				</TracingBeam>
				<div className="flex flex-col w-full mx-auto max-w-5xl">
					<p className="font-mono text-sm mb-2 text-white/35">Generated by</p>
					<div className="flex items-center gap-3 w-full">
						<a href="" className="w-[fit-content]">
							<Image
								src={
									"https://ik.imagekit.io/fabric01/linkx/default.png?updatedAt=1708353019749"
								}
								width={150}
								height={150}
								alt="Author"
								className="cursor-pointer w-9 h-9 rounded-full"
							/>
						</a>
						<div className="flex flex-col gap-1">
							<a href="" className="w-[fit-content]">
								<h2
									style={{ textShadow: "0em 0em 0.3em white" }}
									className="text-base font-bold cursor-pointer hover:underline w-full"
								>
									{"username"}
								</h2>
							</a>
							<div className="flex flex-row text-start">
								{accountInfo.map((info: any, index) => (
									<div className="flex items-start gap-0">
										<img
											className="h-[0.8rem] w-[0.8rem] mr-1 invert"
											src={icons[index]}
										></img>
										<span
											style={{ textShadow: "0em 0em 0.4em white" }}
											className="text-xs font-bold mr-2"
										>
											{info}
										</span>
									</div>
								))}
							</div>
						</div>
					</div>
					<div className="flex items-center gap-3 w-full pt-4 mb-7">
						<TooltipProvider delayDuration={300}>
							<Tooltip>
								<TooltipTrigger>
									<Link
										className={buttonVariants({ variant: "outline" })}
										href={""}
									>
										<BotIcon className="size-5 mx-4 my-2"></BotIcon>
									</Link>
								</TooltipTrigger>
								<TooltipContent
									className="p-0 m-0 border-none outline-none font-mono bg-transparent text-xs font-extralight"
									side="bottom"
								>
									<p style={{ textShadow: "0em 0em 0.3em white" }}>
										Remix generation
									</p>
								</TooltipContent>
							</Tooltip>
						</TooltipProvider>
						<TooltipProvider delayDuration={300}>
							<Tooltip>
								<TooltipTrigger>
									<Link
										className={buttonVariants({ variant: "outline" })}
										href={""}
									>
										<MessageSquareText className="size-4 mx-4 my-2"></MessageSquareText>
									</Link>
								</TooltipTrigger>
								<TooltipContent
									className="p-0 m-0 border-none outline-none font-mono bg-transparent text-xs font-extralight"
									side="bottom"
								>
									<p style={{ textShadow: "0em 0em 0.3em white" }}>
										Add a review
									</p>
								</TooltipContent>
							</Tooltip>
						</TooltipProvider>
						<TooltipProvider delayDuration={300}>
							<Tooltip>
								<TooltipTrigger>
									<Link
										className={buttonVariants({ variant: "outline" })}
										href={""}
									>
										<Bookmark className="size-4 mx-4 my-2"></Bookmark>
									</Link>
								</TooltipTrigger>
								<TooltipContent
									className="p-0 m-0 border-none outline-none font-mono bg-transparent text-xs font-extralight"
									side="bottom"
								>
									<p style={{ textShadow: "0em 0em 0.3em white" }}>
										Add to library
									</p>
								</TooltipContent>
							</Tooltip>
						</TooltipProvider>
					</div>
					<p className="font-mono text-sm mb-2 text-white/60">Reviews</p>
					<div className="container h-[30vh] overflow-y-auto overflow-x-hidden border border-white/15 bg-black/10 border-solid rounded-lg p-5 flex flex-col items-start gap-3 w-full pt-4">
						{reviews.map((rev, index) => (
							<div className="flex flex-col gap-2 mx-auto w-[60rem]">
								<div className="my-2">
									<div className="flex flex-row gap-2">
										<a href="" className="w-[fit-content]">
											<img
												className="w-6 h-6 rounded-full"
												src="/icons/pfp1.png"
											></img>
										</a>
										<a href="" className="w-[fit-content] h-[fit-content]">
											<h2
												style={{ textShadow: "0em 0em 0.3em white" }}
												className="text-sm cursor-pointer hover:underline w-full"
											>
												{rev.author}
											</h2>
										</a>
									</div>
									<p className="text-[14px] p-[0.1rem] mt-1 font-mono text-white/50">
										{rev.content}
									</p>
								</div>
								<div className="mx-auto w-full h-[0.01rem] bg-white/5"></div>
							</div>
						))}
					</div>
				</div>
			</div>
		</main>
	)
}
